# Specify here the OpenWrt Repo URL and Branch
# REPO_URL="https://github.com/openwrt/openwrt"
# REPO_BRANCH="openwrt-19.07"
REPO_URL="https://github.com/OpenWRT-fanboy/OpenW1700k"
REPO_BRANCH="ubi2"
