#!/bin/sh
# Remove the old script include when upgrading with retained configuration.
uci -q delete firewall.bridge_flow_offload
rm -f /usr/share/bridge-flow-offload/apply-rules.sh
rm -f /etc/hotplug.d/iface/51-bridge-flow-offload
# Official fw4 does not use the former custom bridge-table include.
rm -f /usr/share/nftables.d/ruleset-post/30-bridge-offload.nft
exit 0
