#!/bin/sh

# ============================================================
# W1700K default configuration
# ============================================================

# ------------------------------------------------------------
# System timezone
# ------------------------------------------------------------

uci -q set system.@system[0].zonename='Asia/Hong_Kong'
uci -q set system.@system[0].timezone='HKT-8'


# ------------------------------------------------------------
# LuCI language / theme
# ------------------------------------------------------------

uci -q set luci.main.lang='zh_cn'
uci -q set luci.main.mediaurlbase='/luci-static/aurora'


# ------------------------------------------------------------
# Find Wi-Fi radios
# ------------------------------------------------------------

RADIOS_2G=""
RADIOS_5G=""
RADIOS_6G=""

for DEV in $(uci show wireless | \
    sed -n 's/^wireless\.\([^.=]*\)=wifi-device$/\1/p')
do
    BAND="$(uci -q get wireless.${DEV}.band || true)"

    case "$BAND" in
        2g)
            RADIOS_2G="$RADIOS_2G $DEV"
            ;;
        5g)
            RADIOS_5G="$RADIOS_5G $DEV"
            ;;
        6g)
            RADIOS_6G="$RADIOS_6G $DEV"
            ;;
    esac
done


# ------------------------------------------------------------
# 2.4 GHz
# ------------------------------------------------------------

for DEV in $RADIOS_2G; do
    uci -q set wireless.${DEV}.disabled='0'
    uci -q set wireless.${DEV}.country='US'
    uci -q set wireless.${DEV}.channel='1'
    uci -q set wireless.${DEV}.htmode='HT20'
done


# ------------------------------------------------------------
# 5 GHz
# ------------------------------------------------------------

for DEV in $RADIOS_5G; do
    uci -q set wireless.${DEV}.disabled='0'
    uci -q set wireless.${DEV}.country='US'
    uci -q set wireless.${DEV}.channel='36'
    uci -q set wireless.${DEV}.htmode='HE160'
done


# ------------------------------------------------------------
# 6 GHz
# 6 GHz is configured but disabled by default.
# Enable it manually from LuCI when needed.
# ------------------------------------------------------------

for DEV in $RADIOS_6G; do
    uci -q set wireless.${DEV}.disabled='1'
    uci -q set wireless.${DEV}.country='US'
    uci -q set wireless.${DEV}.channel='37'
    uci -q set wireless.${DEV}.htmode='EHT320'
done


# ------------------------------------------------------------
# Remove existing Wi-Fi interface defaults
# ------------------------------------------------------------

for IFACE in $(uci show wireless | \
    sed -n 's/^wireless\.\([^.=]*\)=wifi-iface$/\1/p')
do
    uci -q delete wireless.${IFACE}
done


# ------------------------------------------------------------
# 按频段为每一张网卡建 SSID
# 同频段出现多张网卡时，自动加 -2 / -3 ... 后缀防止 SSID 重名
# ------------------------------------------------------------

create_ssid() {
    # $1=device  $2=SSID基名  $3=加密方式  $4=密码  $5=后缀
    IFACE="$(uci add wireless wifi-iface)"

    uci set wireless.${IFACE}.device="$1"
    uci set wireless.${IFACE}.mode='ap'
    uci set wireless.${IFACE}.network='lan'
    uci set wireless.${IFACE}.ssid="$2$5"
    uci set wireless.${IFACE}.encryption="$3"
    uci set wireless.${IFACE}.key="$4"
}

N=0
for DEV in $RADIOS_2G; do
    N=$((N + 1))
    SUFFIX=""
    [ "$N" -gt 1 ] && SUFFIX="-$N"
    create_ssid "$DEV" 'W1700K' 'psk2' '12345678' "$SUFFIX"
done

N=0
for DEV in $RADIOS_5G; do
    N=$((N + 1))
    SUFFIX=""
    [ "$N" -gt 1 ] && SUFFIX="-$N"
    create_ssid "$DEV" 'W1700K' 'psk2' '12345678' "$SUFFIX"
done

N=0
for DEV in $RADIOS_6G; do
    N=$((N + 1))
    SUFFIX=""
    [ "$N" -gt 1 ] && SUFFIX="-$N"
    create_ssid "$DEV" 'W1700K-6G' 'sae' '12345678' "$SUFFIX"
done


# ------------------------------------------------------------
# Commit
# ------------------------------------------------------------

uci commit system
uci commit luci
uci commit wireless


exit 0
