#!/bin/sh

# ============================================================
# W1700K default configuration
# ============================================================

# ------------------------------------------------------------
# System timezone
# ------------------------------------------------------------

uci -q set system.@system[0].zonename='Asia/Hong_Kong'
uci -q set system.@system[0].timezone='HKT-8'
uci -q set system.@system[0].hostname='W1700K'


# ------------------------------------------------------------
# LuCI language / theme
# ------------------------------------------------------------

uci -q set luci.main.lang='zh-cn'
uci -q set luci.main.mediaurlbase='/luci-static/aurora'


# ------------------------------------------------------------
# Find Wi-Fi radios
# ------------------------------------------------------------

RADIO_2G=""
RADIO_5G=""
RADIO_6G=""

for DEV in $(uci show wireless | \
    sed -n 's/^wireless\.\([^.=]*\)=wifi-device$/\1/p')
do
    BAND="$(uci -q get wireless.${DEV}.band || true)"

    case "$BAND" in
        2g)
            RADIO_2G="$DEV"
            ;;
        5g)
            RADIO_5G="$DEV"
            ;;
        6g)
            RADIO_6G="$DEV"
            ;;
    esac
done


# ------------------------------------------------------------
# 2.4 GHz
# ------------------------------------------------------------

if [ -n "$RADIO_2G" ]; then
    uci -q set wireless.${RADIO_2G}.disabled='0'
    uci -q set wireless.${RADIO_2G}.country='US'
    uci -q set wireless.${RADIO_2G}.channel='1'
    uci -q set wireless.${RADIO_2G}.htmode='EHT20'
    uci -q set wireless.${RADIO_2G}.txpower='23'
fi


# ------------------------------------------------------------
# 5 GHz
# ------------------------------------------------------------

if [ -n "$RADIO_5G" ]; then
    uci -q set wireless.${RADIO_5G}.disabled='0'
    uci -q set wireless.${RADIO_5G}.country='US'
    uci -q set wireless.${RADIO_5G}.channel='36'
    uci -q set wireless.${RADIO_5G}.htmode='EHT160'
    uci -q set wireless.${RADIO_5G}.txpower='23'
fi


# ------------------------------------------------------------
# 6 GHz
# ------------------------------------------------------------

if [ -n "$RADIO_6G" ]; then
    # 6 GHz is configured but disabled by default.
    # Enable it manually from LuCI when needed.
    uci -q set wireless.${RADIO_6G}.disabled='1'
    uci -q set wireless.${RADIO_6G}.country='US'
    uci -q set wireless.${RADIO_6G}.channel='37'
    uci -q set wireless.${RADIO_6G}.htmode='EHT320'
    uci -q set wireless.${RADIO_6G}.txpower='23'
fi


# ------------------------------------------------------------
# Remove existing Wi-Fi interface defaults
# ------------------------------------------------------------

for IFACE in $(uci show wireless | \
    sed -n 's/^wireless\.\([^.=]*\)=wifi-iface$/\1/p')
do
    uci -q delete wireless.${IFACE}
done


# ------------------------------------------------------------
# 2.4 GHz SSID
# ------------------------------------------------------------

if [ -n "$RADIO_2G" ]; then

    IFACE_2G="wifinet2g"
    uci -q delete wireless.${IFACE_2G}
    uci set wireless.${IFACE_2G}=wifi-iface

    uci set wireless.${IFACE_2G}.device="${RADIO_2G}"
    uci set wireless.${IFACE_2G}.mode='ap'
    uci set wireless.${IFACE_2G}.network='lan'
    uci set wireless.${IFACE_2G}.ssid='W1700K'
    uci set wireless.${IFACE_2G}.encryption='psk2+ccmp'
    uci set wireless.${IFACE_2G}.key='12345678'

fi


# ------------------------------------------------------------
# 5 GHz SSID
# ------------------------------------------------------------

if [ -n "$RADIO_5G" ]; then

    IFACE_5G="wifinet5g"
    uci -q delete wireless.${IFACE_5G}
    uci set wireless.${IFACE_5G}=wifi-iface

    uci set wireless.${IFACE_5G}.device="${RADIO_5G}"
    uci set wireless.${IFACE_5G}.mode='ap'
    uci set wireless.${IFACE_5G}.network='lan'
    uci set wireless.${IFACE_5G}.ssid='W1700K'
    uci set wireless.${IFACE_5G}.encryption='psk2+ccmp'
    uci set wireless.${IFACE_5G}.key='12345678'

fi


# ------------------------------------------------------------
# 6 GHz SSID
# ------------------------------------------------------------

if [ -n "$RADIO_6G" ]; then

    IFACE_6G="wifinet6g"
    uci -q delete wireless.${IFACE_6G}
    uci set wireless.${IFACE_6G}=wifi-iface

    uci set wireless.${IFACE_6G}.device="${RADIO_6G}"
    uci set wireless.${IFACE_6G}.mode='ap'
    uci set wireless.${IFACE_6G}.network='lan'
    uci set wireless.${IFACE_6G}.ssid='W1700K-6G'
    uci set wireless.${IFACE_6G}.encryption='sae+ccmp'
    uci set wireless.${IFACE_6G}.key='12345678'

fi


# ------------------------------------------------------------
# Commit
# ------------------------------------------------------------

uci commit system
uci commit luci
uci commit wireless


exit 0
