name: update-all

on:
  schedule:
    - cron: '22 * * * *'
  workflow_dispatch:

permissions: {actions: write, contents: write}

env:
  REMOTE_REPOSITORY: OpenWRT-fanboy/OpenW1700k

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.status.outputs.updated }}
    steps:
      - name: Check for new commits on openwrt/openwrt
        id: check
        run: |
          HEAD_SHA=$(git ls-remote https://github.com/openwrt/openwrt.git main | awk '{print $1}')
          echo "head_sha=$HEAD_SHA" >> "$GITHUB_OUTPUT"

      - name: Cache openwrt head SHA
        id: cache
        uses: actions/cache@v5
        with:
          path: .openwrt_head_sha
          key: openwrt-head-${{ steps.check.outputs.head_sha }}

      - name: Set update status
        id: status
        run: |
          if [ "${{ steps.cache.outputs.cache-hit }}" = "true" ]; then
            echo "updated=false" >> "$GITHUB_OUTPUT"
          else
            echo "updated=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Delete old cache
        if: steps.status.outputs.updated == 'true'
        run: |
          gh cache list \
            --repo ${{ github.repository }} \
            --json id,key \
            --jq '.[] | select(.key | startswith("openwrt-head-")) | .id' | \
          xargs -r -I{} gh cache delete {} \
            --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Save head SHA to cache
        if: steps.status.outputs.updated == 'true'
        run: echo "${{ steps.check.outputs.head_sha }}" > .openwrt_head_sha

  update:
    needs: check
    if: needs.check.outputs.updated == 'true'
    name: Update ${{ matrix.environment }} branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [main, snapshot, ubi2-oc-auto]
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout remote repository
        uses: actions/checkout@main
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ matrix.environment }}
          fetch-depth: 0
          token: ${{ secrets.REPO_SECRET }}
      - name: Pull updates then push
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git remote add openwrt https://github.com/openwrt/openwrt.git
          git remote update
          git rebase openwrt/main
          git push --force-with-lease
